services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    ports:
      - "3015:3015"
    env_file:
      - ./frontend/.env.production
    restart: unless-stopped
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://cyanki:cyanki_pass@db:5432/cyanki_prod_db
      - ENVIRONMENT=production
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=cyanki
      - POSTGRES_PASSWORD=cyanki_pass
      - POSTGRES_DB=cyanki_prod_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    restart: unless-stopped

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    env_file:
      - .env
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    depends_on:
      - frontend

volumes:
  postgres_data_prod:
